version: '3.3'

services:
  devita_crawler:
    container_name: devita_crawler
    image: italia/developers-italia-backend
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./crawler/domains.yml:/go/developers-italia-backend/crawler/domains.yml
