on:
  push:
    branches: [ legacy ]
  pull_request:
    branches: [ legacy ]

jobs:
  yml-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ibiqlik/action-yamllint@v1.0.0
      with:
        # File(s) or Directory, separate by space if multiple files or folder are specified
        file_or_dir: publishers*.yml
        # Return non-zero exit code on warnings as well as errors
        strict: true
